version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    pid: host
    cgroup: host
    environment:
      DD_TRACE_AGENT_HOSTNAME: "datadog-agent"
      DD_TRACE_AGENT_PORT: "8126"
      DD_SERVICE: "flask-dd-lab"
      DD_ENV: "dd-sg-lab"
      DD_VERSION: "1.0.0"
      DD_RUNTIME_METRICS_ENABLED: "true"
      DD_AGENT_HOST: "datadog-agent"
    depends_on:
      - datadog-agent

  datadog-agent:
    image: "datadog/agent:latest"
    environment:
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_API_KEY: PLACE API KEY HERE
      DD_PROCESS_AGENT_ENABLED: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
    ports:
      - "8126:8126"
      - "8125:8125/udp"
    volumes:
     - /etc/passwd:/etc/passwd:ro
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro